# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude : [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor", "gems"]

highlighter : pygments

sheets :
  courses :
    key     : 1sKFE3vyP6lszBn8Xm86rNsS7XZKW5_jSvCW04XywBq4
    object  : Course
    types   : ['Undergraduate', 'Graduate']

  people  :
    key     : 1h_nDcUDNcrCjZPbJSzdXNscRXA6UbTvPzUrKDEEcgYw
    object  : Person
    types   : ['Faculty','Students','Alumni']

  labs    :
    key     : 1lvqQrnJzMK39zGHlLXJTtkkdDmrQ3iCOes2IIqFiom0

flickr :
  hcc_photos :
    set : '72157646414725101'

data_directory : './_data'

credentials: _secret_config.yml

title : Human Centered Computing
tagline: Home of Human Centered Computing at University of Colorado Boulder

#My variables, accessed at site.[whatever]
IMG_PATH : /assets/images
CSS_PATH : /assets/css
JS_PATH  : /assets/js

author :
  name : HCC @ CU

JB :
  version : 0.3.0

  analytics :
    provider : google
    google :
        tracking_id : 'UA-123-12'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
